mutation Login($loginVariables: LoginInput!) {
    login(loginVariables: $loginVariables) {
        token
    }
}

mutation CreateUser($variable: UserInput!) {
    createUser(variable: $variable) {
        token
    }
}

mutation CreateBuilds($variables: BuildsInput!) {
    createBuilds(variables: $variables) {
        id
        name
        address
        estrato
        lont_size
        square_feet
    }
}