mutation Login($loginVariables: LoginInput!) {
    login(loginVariables: $loginVariables) {
        token
    }
}

mutation CreateUser($variable: UserInput!) {
    createUser(variable: $variable) {
        token
    }
}

mutation ForgotPassword($email: String!) {
    forgotPassword(email: $email) {
        mail
    }
}


mutation RecoverPassword($recoverVariables: RecoverPasswordInput!) {
    recoverPassword(recoverVariables: $recoverVariables) {
        mail
    }
}
