mutation CreateBuilds($variables: BuildsInput!) {
    createBuilds(variables: $variables) {
        id
        name
        description
        propertyType
        address
        numberRooms
        numberBathrooms
        stratum
        lotArea
        lotMeters
        parkingLot
        imgName
        imgDescription
        price
        managementValue
        othersCost
        status
    }
}

mutation UpdateBuilds($fields: BuildsUpdateInput!, $updateBuildsId: Int!) {
    updateBuilds(fields: $fields, id: $updateBuildsId) {
        id
        name
        description
        propertyType
        address
        numberRooms
        numberBathrooms
        stratum
        lotArea
        lotMeters
        parkingLot
        price
        imgs {
            id
            url
        }
        managementValue
        othersCost
        status
    }
}

mutation DeleteBuilds($deleteBuildsId: Int!) {
    deleteBuilds(id: $deleteBuildsId)
}

query GetBuilds {
    Builds {
        id,
        name
        description
        propertyType
        address
        numberRooms
        numberBathrooms
        stratum
        lotArea
        lotMeters
        user_id
        parkingLot
        imgs {
            id
            url
        }
        price
        managementValue
        othersCost
        status
    }
}

query GetBuildById($id: Int!) {
    BuildsById(id: $id) {
        id
        name
        description
        propertyType
        address
        numberRooms
        numberBathrooms
        stratum
        lotArea
        lotMeters
        user_id
        parkingLot
        imgs {
            id
            url
        }
        price
        managementValue
        othersCost
        status
    }
}
