mutation CreateBuilds($variables: BuildsInput!) {
    createBuilds(variables: $variables) {
        id
    }
}

query GetBuilds {
    Builds {
        id,
        name
        description
        propertyType
        address
        numberRooms
        numberBathrooms
        stratum
        lotArea
        user_id
        parkingLot
        imgName
        imgDescription
        price
        managementValue
        othersCost
    }
}

query GetBuildById($id: Int!) {
    BuildsById(id: $id) {
        id
        name
        description
        propertyType
        address
        numberRooms
        numberBathrooms
        stratum
        lotArea
        user_id
        parkingLot
        imgName
        imgDescription
        price
        managementValue
        othersCost
        status
    }
}